export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_CINEMA_BRAND="GET_LIST_CINEMA_BRAND";
export const GET_LIST_BRANCH="GET_LIST_BRANCH";
export const GET_LIST_MOVIE_BRAND="GET_LIST_MOVIE_BRAND";
// Huy viet
export const GET_DETAIL_MOVIE="GET_DETAIL_MOVIE";
export const GET_CINEMA="GET_CINEMA";
export const GET_LOGO_CINEMA="GET_LOGO_CINEMA";
// Huy viet
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const GET_BOOTH_INFO = "GET_BOOTH_INFO";
export const ADD_SEAT_USER_CHOOSE = "ADD_SEAT_USER_CHOOSE";
export const BOOKING_SUCCESS = "BOOKING_SUCCESS";
export const GET_BOOTH_INFO_FAIL = "GET_BOOTH_INFO_FAIL";
export const GET_LIST_USER = "GET_LIST_USER";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const ON_SAVE_USER_SUCCESS = "ON_SAVE_USER_SUCCESS";
export const PUT_TRAILER_SRC = "PUT_TRAILER_SRC";
export const GET_MOVIE_ONSCREEN = "GET_MOVIE_ONSCREEN";