export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_CINEMA_BRAND="GET_LIST_CINEMA_BRAND";
export const GET_LIST_BRANCH="GET_LIST_BRANCH";
export const GET_LIST_MOVIE_BRAND="GET_LIST_MOVIE_BRAND";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_SIGN_OUT = "USER_SIGN_OUT";
export const GET_BOOTH_INFO = "GET_BOOTH_INFO";
export const ADD_SEAT_USER_CHOOSE = "ADD_SEAT_USER_CHOOSE";