export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_CINEMA_BRAND="GET_LIST_CINEMA_BRAND";
export const GET_LIST_BRANCH="GET_LIST_BRANCH";
export const GET_LIST_MOVIE_BRAND="GET_LIST_MOVIE_BRAND";